In [95]:
import numpy as np
import pandas as pd
x=np.array([[0,0,1],
           [0,1,1],
           [1,0,1],
           [1,1,1],
           [1,0,1],
           [1,1,1]])

In [96]:
y=np.array([[0],
          [1],
          [1],
          [0],
          [1],
          [0]])

In [63]:
np.random.seed(101)
w1=np.random.random((3,5))
w2=np.random.random((5,7))
w3=np.random.random((7,5))
w4=np.random.random((5,1))

[[0.51639863 0.57066759 0.02847423 0.17152166 0.68527698]
 [0.83389686 0.30696622 0.89361308 0.72154386 0.18993895]
 [0.55422759 0.35213195 0.1818924  0.78560176 0.96548322]]


In [97]:
###sigmoid activation function:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [98]:
##Error function:
def mse(y,ycap):
    return ((y-ycap)**2).mean()

In [99]:
def derivative(x):
    return x*(x-1)

In [94]:
w=[np.array(w1),np.array(w2),np.array(w3),np.array(w4)]

In [100]:
def train(x,y,w,iter,conv=0.000000001):
    w1=w[0]
    w2=w[1]
    w3=w[2]
    w4=w[3]
    perr=0
    j=0
    for i in range(iter):
        l1=sigmoid(x.dot(w1))
        l2=sigmoid(l1.dot(w2))
        l3=sigmoid(l2.dot(w3))
        l4=sigmoid(l3.dot(w4))
        cerr=mse(y,l4)
        
        diff=abs(perr-cerr)
        if diff<=conv:
            print("training  completed after ",i+1,"iteration")
            j=1
            break
        if i%250==0:
            print("current error at ",i+1,"iterations")
        e4=y-l4
        delta4=e4*derivative(l4)
        e3=delta4.dot(w4.T)
        delta3=e3*derivative(l3)
        e2=delta3.dot(w3.T)
        delta2=e2*derivative(l2)
        e1=delta2.dot(w2.T)
        delta1=e1*derivative(l1)
        w1+=x.T.dot(delta1)
        w2+=l1.T.dot(delta2)
        w3+=l2.T.dot(delta3)
        w4+=l3.T.dot(delta4)
        perr=cerr
    if j==0:
        print("Training not completed")
    return [w1,w2,w3,w4]    
            

In [101]:
print(len(w))

4


In [69]:
theta=train(x,y,w,6000)

current error at  1 iterations
current error at  251 iterations
current error at  501 iterations
current error at  751 iterations
current error at  1001 iterations
current error at  1251 iterations
current error at  1501 iterations
current error at  1751 iterations
current error at  2001 iterations
current error at  2251 iterations
training  completed after  2363 iteration


In [71]:
print(w1)

[[0.51639863 0.57066759 0.02847423 0.17152166 0.68527698]
 [0.83389686 0.30696622 0.89361308 0.72154386 0.18993895]
 [0.55422759 0.35213195 0.1818924  0.78560176 0.96548322]]


In [72]:
theta[0]

array([[0.50723469, 0.55557787, 0.01023172, 0.16121979, 0.67671674],
       [0.82460744, 0.29176219, 0.87514993, 0.71108076, 0.18132363],
       [0.52859358, 0.31932029, 0.14295647, 0.7602993 , 0.94412283]])

In [102]:
#predicted function:
def predict(x,w):
    r=x
    for v in w:
        r=sigmoid(r.dot(v))
    return r       

In [105]:
ycap=predict(x,theta)
 print(ycap)

[[0.99992821]
 [0.99993415]
 [0.99993227]
 [0.99993648]
 [0.99993227]
 [0.99993648]]


In [80]:
print(np.c_[y.ravel(),ycap.ravel()])

[[0. 1.]
 [1. 1.]
 [1. 1.]
 [0. 1.]
 [1. 1.]
 [0. 1.]]


In [106]:
ycap[ycap>0.5]=1
ycap[ycap<0.5]=0
print(ycap)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [82]:
print(np.c_[y.ravel(),ycap.ravel()])

[[0. 1.]
 [1. 1.]
 [1. 1.]
 [0. 1.]
 [1. 1.]
 [0. 1.]]


In [107]:
##accuracy function:
def acc_clf(y,ycap):
    r=y==ycap
    pcnt=r[r==True].size
    n=y.size
    acc=pcnt/n*100
    return acc    

In [108]:
acc_clf(y,ycap)

50.0

In [110]:
newdata=np.array([[1,1,0],
                [1,0,1],
                [1,1,1],
                [0,0,1]])
predictions=predict(newdata,theta)
print(predictions)


[[0.99993321]
 [0.99993227]
 [0.99993648]
 [0.99992821]]


In [115]:
p=predictions
p[p>0.5]=1
p[p<0.5]=0
print(p)

[[1.]
 [1.]
 [1.]
 [1.]]
